services:
    app:
        container_name: frankenphp_new
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        restart: always
        ports:
            - "8081:80"
        volumes:
            - ./app:/app/public
        tty: true

    database: 
        image: mysql:latest 
        container_name: random-fight-db
        volumes: 
            - ./init.sql:/data/application/init.sql
            - datavolume:/var/lib/mysql
        command: --init-file /data/application/init.sql
        environment: 
            MYSQL_DATABASE: random_fight
            MYSQL_ROOT_PASSWORD: root
        ports: 
            - "3307:3306"        
    
    phpmyadmin: 
        image: phpmyadmin/phpmyadmin:latest
        container_name: my_phpmyadmin
        environment: 
            PMA_HOST: database
        ports: 
            - "8080:80"
        depends_on: 
            - database

volumes:
    datavolume:

    

